{
 "title": "MPC",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "satellites",
    "label": "satellites",
    "query": "SELECT\n distinct data ->>'id' as metric\nFROM\n  cyclopee.sensor \nGROUP BY data\nORDER BY metric ASC"
   }
  ]
 },
 "panels": [
  { "title": "Cyclopée", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cyclopée elevation",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "meters" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  data ->>'id' as metric ,\n  (data ->>'elv')::numeric - ((data ->>'urm')::numeric/1000) as \"elv-urm\",\n  (data ->>'elv')::numeric - ((data ->>'a01')::numeric/1000) as \"elv-a01\",\n  (data ->>'elv')::numeric as elv\nFROM\n  cyclopee.sensor \nWHERE\n  $__timeFilter(time) AND \n  data ->>'id' IN ($satellites)\n  --AND data ->>'dist' IS NOT NULL\n  AND (data ->>'urm')::numeric > 1100\n  AND (data ->>'urm')::numeric < 1500\n  AND (data ->>'a01')::numeric > 1100\n  AND (data ->>'a01')::numeric < 1500\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Cyclopée Distance + T°C",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 9, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  data ->>'id' as metric ,\n  (data ->>'urm')::numeric as urm,\n  (data ->>'a01')::numeric as a01,\n  (data ->>'temp')::numeric as temperature\nFROM\n  cyclopee.sensor \nWHERE\n  $__timeFilter(time) AND \n  data ->>'id' IN ($satellites)\n  --AND data ->>'dist' IS NOT NULL\n  AND (data ->>'urm')::numeric > 1100\n  AND (data ->>'urm')::numeric < 1500\n  AND (data ->>'a01')::numeric > 1100\n  AND (data ->>'a01')::numeric < 1500\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Carte",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  data ->>'id' as metric ,\n  (data ->>'lat')::numeric as lat,\n   (data ->>'lon')::numeric as lon\nFROM\n  cyclopee.sensor \nWHERE\n  $__timeFilter(time) AND \n  data ->>'id' IN ($satellites)\n--  AND data ->>'dist' IS NOT NULL\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Cyclopée elevation less offset",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "meters" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  data ->>'id' as metric ,\n  (data ->>'elv')::numeric - ((data ->>'urm')::numeric/1000)- 0.109 as \"elv-urm\",\n  (data ->>'elv')::numeric - ((data ->>'a01')::numeric/1000)- 0.086 as \"elv-a01\"\nFROM\n  cyclopee.sensor \nWHERE\n  $__timeFilter(time) AND \n  data ->>'id' IN ($satellites)\n  --AND data ->>'dist' IS NOT NULL\n  AND (data ->>'urm')::numeric > 1100\n  AND (data ->>'urm')::numeric < 1500\n  AND (data ->>'a01')::numeric > 1100\n  AND (data ->>'a01')::numeric < 1500\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "cyclopée absolu zéro hydro + marégraphe AIX",
   "type": "timeseries",
   "description": "data gnss - distance accoustique - offset capteurs - geoid raf18 + zéro hydro LR \n\nhttps://www.sonel.org/IMG/pdf/R10002_LaRochelle_20100729.pdf\n\nhttps://data.shom.fr/donnees/refmar/189#001=eyJjIjpbLTE2MjYwMy4wODY5MDE4MDY4LDU3OTE4MTcuMTI5NDg3OTMzXSwieiI6MTAsInIiOjAsImwiOlt7InR5cGUiOiJSRUZNQVIiLCJpZGVudGlmaWVyIjoiUkVGTUFSL09USEVSIiwib3BhY2l0eSI6MSwidmlzaWJpbGl0eSI6dHJ1ZX0seyJ0eXBlIjoiUkVGTUFSIiwiaWRlbnRpZmllciI6IlJFRk1BUi9ST05JTSIsIm9wYWNpdHkiOjEsInZpc2liaWxpdHkiOnRydWV9LHsidHlwZSI6IklOVEVSTkFMX0xBWUVSIiwiaWRlbnRpZmllciI6IkZEQ19HRUJDT19QWVItUE5HXzM4NTdfV01UUyIsIm9wYWNpdHkiOjEsInZpc2liaWxpdHkiOnRydWV9XX0=",
   "gridPos": { "h": 14, "w": 14, "x": 10, "y": 15 },
   "targets": [
    {
     "columns": [
      { "selector": "timestamp", "text": "time", "type": "timestamp" },
      { "selector": "value", "text": "Maregraphe AIX", "type": "number" }
     ],
     "source": "url",
     "type": "json",
     "url": "https://services.data.shom.fr/maregraphie/observation/json/189?sources=1&dtStart=${__from:date:YYYY-MM-DDTHH}:${__from:date:mm}:${__from:date:ss}&dtEnd=${__to:date:YYYY-MM-DDTHH}:${__to:date:mm}:${__to:date:ss}&interval=5&=&_=1678095706088",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "rawSql": "SELECT\n  time - interval'2 hour',\n  data ->>'id' as metric ,\n  (data ->>'elv')::numeric - ((data ->>'urm')::numeric/1000)- 0.109 - 46.941 + 3.447 as \"elv-urm-zeroHydro\",\n  (data ->>'elv')::numeric - ((data ->>'a01')::numeric/1000)- 0.086 - 46.941 + 3.447 as \"elv-a01-zeroHydro\"\nFROM\n  cyclopee.sensor \nWHERE\n  $__timeFilter(time) AND \n  data ->>'id' IN ($satellites)\n  --AND data ->>'dist' IS NOT NULL\n  AND (data ->>'urm')::numeric > 1100\n  AND (data ->>'urm')::numeric < 1500\n  AND (data ->>'a01')::numeric > 1100\n  AND (data ->>'a01')::numeric < 1500\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Air",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "T°C",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  data ->>'id' as metric ,\n  (data ->>'BME_Temperature')::numeric as BME_Temperature,\n  (data ->>'Co2_Temperature')::numeric as Co2_Temperature\n\nFROM\n  cyclopee.sensor \nWHERE\n  $__timeFilter(time) AND \n  data ->>'id' IN ($satellites)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Humidité",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  data ->>'id' as metric ,\n  (data ->>'BME_Humidity')::numeric as BME_Humidity,\n  (data ->>'Co2_Humidity')::numeric as Co2_Humidity\n\nFROM\n  cyclopee.sensor \nWHERE\n  $__timeFilter(time) AND \n  data ->>'id' IN ($satellites)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Pression",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "pressurembar" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  data ->>'id' as metric ,\n  (data ->>'BME_Pressure')::numeric as BME_Pressure\n\nFROM\n  cyclopee.sensor \nWHERE\n  $__timeFilter(time) AND \n  data ->>'id' IN ($satellites)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "CO2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  data ->>'id' as metric ,\n  (data ->>'Co2')::numeric as Co2\n\nFROM\n  cyclopee.sensor \nWHERE\n  $__timeFilter(time) AND \n  data ->>'id' IN ($satellites)\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Environnement",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Turbidity",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "NTU" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  data ->>'id' as metric ,\n  (data ->>'turb')::numeric as Turbidity,\n  (data ->>'raw_turb')::numeric as Rawturb\n  \nFROM\n  cyclopee.sensor \nWHERE\n  $__timeFilter(time) AND \n  data ->>'id' IN ($satellites)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "Température",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  data ->>'id' as metric ,\n  (data ->>'temp')::numeric as Temperature\n  \nFROM\n  cyclopee.sensor \nWHERE\n  $__timeFilter(time) AND \n  data ->>'id' IN ($satellites)\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Audit data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 14, "w": 7, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\n distinct data ->>'id' as metric ,\n jsonb_object_keys(data) as key\nFROM\n  cyclopee.sensor \nWHERE\n  $__timeFilter(time) AND \n  data ->>'id' IN ($satellites)\nGROUP BY data,key\nORDER BY metric,key ASC"
      }
     ]
    }
   ]
  },
  {
   "title": "Météo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true
  },
  {
   "title": "OIO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "OIO",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n  time,\n  data ->>'id' as metric ,\n  (data ->>'GravityPH')::numeric as Ph,\n   --(data ->>'Temperature')::numeric as temperature,\n   (data ->>'GravityEC')::numeric as EC,\n   (data ->>'GravityTurbidity')::numeric as Turbidity\nFROM\n  cyclopee.sensor \nWHERE\n  $__timeFilter(time) AND \n  data ->>'id' IN ($satellites)\nORDER BY 1,2"
      }
     ]
    }
   ]
  }
 ]
}